id: P004274
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG09763
  title: དཔལ་འབའ་རོམ་པ་ཆེན་པོའི་བརྒྱུད་པ་གསེར་གྱི་ཕྲེང་བ
  author: ''
  volumes:
    a9e89499767f4199999c5d379e9dbc27:
      image_group_id: I00KG09845
      title: ''
      volume_number: 1
      total_pages: 81
