id: P004274
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:06:39.918904
source_metadata:
  id: bdr:W00KG09763
  title: དཔལ་འབའ་རོམ་པ་ཆེན་པོའི་བརྒྱུད་པ་གསེར་གྱི་ཕྲེང་བ
  author: ''
  volumes:
    a9e89499767f4199999c5d379e9dbc27:
      image_group_id: I00KG09845
      title: ''
      volume_number: 1
      total_pages: 81
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
