id: IFF65CAA4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T15:35:13+00:00'
last_modified: '2022-06-07T21:36:09.821704+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG09763
  title: དཔལ་འབའ་རོམ་པ་ཆེན་པོའི་བརྒྱུད་པ་གསེར་གྱི་ཕྲེང་བ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '7179':
      image_group_id: I00KG09845
      title: ''
      total_pages: 81
      order: 1
      base_file: 7179.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
