id: IFF65CAA4
legacy_id: P004274
ocr_import_info:
  bdrc_scan_id: W00KG09763
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T15:34:39'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T12:42:41.574196+00:00'
last_modified: 2022-08-29 20:42:52.489828
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG09763
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00KG09763
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་འབའ་རོམ་པ་ཆེན་པོའི་བརྒྱུད་པ་གསེར་གྱི་ཕྲེང་བ།
  author: སྐུ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.8738782251674443
  ocr_word_median_confidence_index: 0.949999988079071
quality: null
bases:
  I00KG09845:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG09845
      total_pages: 81
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG09845.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.8738782251674443
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
